export const API_ENDPOINTS = {
  AUTH: {
    REGISTER: '/auth/register',
    LOGIN: '/auth/login',
    LOGOUT: '/auth/logout',
    PROFILE: '/auth/profile',
    CHANGE_PASSWORD: '/auth/change-password',
    FORGOT_PASSWORD: '/auth/forgot-password',
    RESET_PASSWORD: '/auth/reset-password',
  },
  COINS: {
    GET_ALL: '/coins',
    GET_BY_ID: (id) => `/coins/${id}`,
    SEARCH: '/search/coins',
    LATEST: '/coins/latest',
    TOP_GAINERS: '/coins/top-gainers',
    TOP_LOSERS: '/coins/top-losers',
    TOP_MARKET_CAP: '/coins/top-market-cap',
    TOP_VOLUME: '/coins/top-volume',
    TRENDING: '/coins/trending',
    MARKET_SUMMARY: '/coins/market/summary',
    FILTER: '/coins',
    HISTORY: (coinId) => `/coins/history/${coinId}`,
    PRICE: (coinId) => `/coins/price/${coinId}`,
    MARKET_CAP: (coinId) => `/coins/market-cap/${coinId}`,
    VOLUME: (coinId) => `/coins/volume/${coinId}`,
    PERFORMANCE: (coinId) => `/coins/performance/${coinId}`,
    RETURNS: (coinId) => `/coins/returns/${coinId}`,
    VOLATILITY: (coinId) => `/coins/volatility/${coinId}`,
    COMPARE: (coin1, coin2, coin3) =>
      coin3 ? `/coins/compare/${coin1}/${coin2}/${coin3}` : `/coins/compare/${coin1}/${coin2}`,
    RECOMMENDATIONS: '/coins/recommendations',
    SIMULATE: '/coins/portfolio/simulate',
  },
  ANALYTICS: {
    MARKET_SUMMARY: '/analytics/market/summary',
    PRICE_ANALYTICS: (coinId) => `/analytics/price/history/${coinId}`,
    VOLUME_ANALYTICS: '/analytics/volume/highest',
    RETURN_ANALYTICS: '/analytics/returns/top',
    VOLATILITY_ANALYTICS: '/analytics/volatility/high',
  },
  WATCHLIST: {
    GET_ALL: '/bookmarks',
    ADD: (coinId) => `/bookmarks/${coinId}`,
    GET_BY_ID: (id) => `/bookmarks/${id}`,
    UPDATE: (id) => `/bookmarks/${id}`,
    DELETE: (id) => `/bookmarks/${id}`,
    CHECK: (coinId) => `/bookmarks/check/${coinId}`,
    ANALYTICS: '/bookmarks/analytics/summary',
    TRENDING: '/bookmarks/trending',
  },
  STATS: {
    MARKET_CAP: '/stats/market-cap',
    AVERAGE_PRICE: '/stats/average-price',
    AVERAGE_VOLUME: '/stats/average-volume',
    HIGHEST_MARKET_CAP: '/stats/highest-market-cap',
    HIGHEST_VOLUME: '/stats/highest-volume',
    TOP_GAINERS: '/stats/top-gainers',
    TOP_LOSERS: '/stats/top-losers',
    MONTHLY_ANALYSIS: '/stats/monthly-analysis',
    COIN_COUNT: '/stats/coin-count',
    RANK_DISTRIBUTION: '/stats/rank-distribution',
    PRICE_DISTRIBUTION: '/stats/price-distribution',
    VOLATILITY_DISTRIBUTION: '/stats/volatility-distribution',
    MARKET_SUMMARY: '/stats/market-summary',
    DAILY_ANALYSIS: '/stats/daily-analysis',
    YEARLY_ANALYSIS: '/stats/yearly-analysis',
  },
  PORTFOLIO: {
    GET_ALL: '/portfolio',
    ADD: '/portfolio',
    GET_BY_ID: (id) => `/portfolio/${id}`,
    UPDATE: (id) => `/portfolio/${id}`,
    DELETE: (id) => `/portfolio/${id}`,
    OVERVIEW: '/portfolio/dashboard/overview',
    ANALYTICS_SUMMARY: '/portfolio/analytics/summary',
    ANALYTICS_DISTRIBUTION: '/portfolio/analytics/distribution',
    ANALYTICS_HISTORY: '/portfolio/analytics/history',
  },
};

export default API_ENDPOINTS;
