export const API_ENDPOINTS = {
  AUTH: {
    REGISTER: '/api/v1/auth/register',
    LOGIN: '/api/v1/auth/login',
    LOGOUT: '/api/v1/auth/logout',
    PROFILE: '/api/v1/auth/profile',
    CHANGE_PASSWORD: '/api/v1/auth/change-password',
    FORGOT_PASSWORD: '/api/v1/auth/forgot-password',
    RESET_PASSWORD: '/api/v1/auth/reset-password',
  },
  COINS: {
    GET_ALL: '/api/v1/coins',
    GET_BY_ID: (id) => `/api/v1/coins/${id}`,
    SEARCH: '/api/v1/search/coins',
    LATEST: '/api/v1/coins/latest',
    TOP_GAINERS: '/api/v1/coins/top-gainers',
    TOP_LOSERS: '/api/v1/coins/top-losers',
    TOP_MARKET_CAP: '/api/v1/coins/top-market-cap',
    TOP_VOLUME: '/api/v1/coins/top-volume',
    TRENDING: '/api/v1/coins/trending',
    MARKET_SUMMARY: '/api/v1/coins/market/summary',
    FILTER: '/api/v1/coins',
    HISTORY: (coinId) => `/api/v1/coins/history/${coinId}`,
    PRICE: (coinId) => `/api/v1/coins/price/${coinId}`,
    MARKET_CAP: (coinId) => `/api/v1/coins/market-cap/${coinId}`,
    VOLUME: (coinId) => `/api/v1/coins/volume/${coinId}`,
    PERFORMANCE: (coinId) => `/api/v1/coins/performance/${coinId}`,
    RETURNS: (coinId) => `/api/v1/coins/returns/${coinId}`,
    VOLATILITY: (coinId) => `/api/v1/coins/volatility/${coinId}`,
    COMPARE: (coin1, coin2, coin3) =>
      coin3 ? `/api/v1/coins/compare/${coin1}/${coin2}/${coin3}` : `/api/v1/coins/compare/${coin1}/${coin2}`,
    RECOMMENDATIONS: '/api/v1/coins/recommendations',
    SIMULATE: '/api/v1/coins/portfolio/simulate',
  },
  ANALYTICS: {
    MARKET_SUMMARY: '/api/v1/analytics/market/summary',
    PRICE_ANALYTICS: (coinId) => `/api/v1/analytics/price/history/${coinId}`,
    VOLUME_ANALYTICS: '/api/v1/analytics/volume/highest',
    RETURN_ANALYTICS: '/api/v1/analytics/returns/top',
    VOLATILITY_ANALYTICS: '/api/v1/analytics/volatility/high',
  },
  WATCHLIST: {
    GET_ALL: '/api/v1/bookmarks',
    ADD: (coinId) => `/api/v1/bookmarks/${coinId}`,
    GET_BY_ID: (id) => `/api/v1/bookmarks/${id}`,
    UPDATE: (id) => `/api/v1/bookmarks/${id}`,
    DELETE: (id) => `/api/v1/bookmarks/${id}`,
    CHECK: (coinId) => `/api/v1/bookmarks/check/${coinId}`,
    ANALYTICS: '/api/v1/bookmarks/analytics/summary',
    TRENDING: '/api/v1/bookmarks/trending',
  },
  STATS: {
    MARKET_CAP: '/api/v1/stats/market-cap',
    AVERAGE_PRICE: '/api/v1/stats/average-price',
    AVERAGE_VOLUME: '/api/v1/stats/average-volume',
    HIGHEST_MARKET_CAP: '/api/v1/stats/highest-market-cap',
    HIGHEST_VOLUME: '/api/v1/stats/highest-volume',
    TOP_GAINERS: '/api/v1/stats/top-gainers',
    TOP_LOSERS: '/api/v1/stats/top-losers',
    MONTHLY_ANALYSIS: '/api/v1/stats/monthly-analysis',
    COIN_COUNT: '/api/v1/stats/coin-count',
    RANK_DISTRIBUTION: '/api/v1/stats/rank-distribution',
    PRICE_DISTRIBUTION: '/api/v1/stats/price-distribution',
    VOLATILITY_DISTRIBUTION: '/api/v1/stats/volatility-distribution',
    MARKET_SUMMARY: '/api/v1/stats/market-summary',
    DAILY_ANALYSIS: '/api/v1/stats/daily-analysis',
    YEARLY_ANALYSIS: '/api/v1/stats/yearly-analysis',
  },
  PORTFOLIO: {
    GET_ALL: '/api/v1/portfolio',
    ADD: '/api/v1/portfolio',
    GET_BY_ID: (id) => `/api/v1/portfolio/${id}`,
    UPDATE: (id) => `/api/v1/portfolio/${id}`,
    DELETE: (id) => `/api/v1/portfolio/${id}`,
    OVERVIEW: '/api/v1/portfolio/dashboard/overview',
    ANALYTICS_SUMMARY: '/api/v1/portfolio/analytics/summary',
    ANALYTICS_DISTRIBUTION: '/api/v1/portfolio/analytics/distribution',
    ANALYTICS_HISTORY: '/api/v1/portfolio/analytics/history',
  },
};

export default API_ENDPOINTS;
